import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Sidebar from '../components/Sidebar';
import NotificationDropdown from '../components/NotificationDropdown';
import ProfileDropdown from '../components/ProfileDropdown';
import Icon from '../components/Icon';
import { supabase } from '../lib/supabaseClient';
import { checkAchievements } from '../lib/achievementService';
import { useUserProfile } from '../context/UserProfileContext';

const DEFAULT_ACHIEVEMENTS = [
  { id: 'pioneer', title: 'Pioneer', description: 'Bergabung dengan Harin Learning.', icon_name: 'history_edu', color_class: 'bg-primary-container' },
  { id: 'first_step', title: 'First Step', description: 'Mengambil kursus pertama.', icon_name: 'rocket_launch', color_class: 'bg-secondary-container' },
  { id: 'scholar', title: 'Scholar', description: 'Menyelesaikan 1 kursus.', icon_name: 'workspace_premium', color_class: 'bg-tertiary-container' },
  { id: 'author', title: 'Author', description: 'Menulis postingan blog pertama.', icon_name: 'edit_note', color_class: 'bg-primary-fixed' },
  { id: 'top_student', title: 'Top Student', description: 'Memiliki 5+ kursus aktif.', icon_name: 'star', color_class: 'bg-secondary-fixed' }
];

const Achievements = () => {
  const navigate = useNavigate();
  const { profile } = useUserProfile();
  const isGuest = profile.isGuest;
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState({ certificates: 0, badges: 0 });
  const [certificates, setCertificates] = useState([]);
  const [earnedBadges, setEarnedBadges] = useState([]);
  const [lockedBadges, setLockedBadges] = useState([]);
  const [selectedCertForPreview, setSelectedCertForPreview] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      const { data: { session } } = await supabase.auth.getSession();

      if (!session && !isGuest) {
        navigate('/login');
        return;
      }

      if (session) {
        // Check new achievements automatically
        await checkAchievements(session.user.id);

        const uid = session.user.id;

        const [certRes, earnedAchRes, allAchRes, enrollmentRes] = await Promise.all([
          // 1. Get certificates issued by teacher from certificates table
          supabase
            .from('certificates')
            .select('id, course_id, issued_at, certificate_url, courses(title, category, image_url)')
            .eq('user_id', uid)
            .order('issued_at', { ascending: false }),

          // 2. Get earned badges
          supabase
            .from('user_achievements')
            .select('achievement_id')
            .eq('user_id', uid),

          // 3. Get all master achievements
          supabase
            .from('achievements')
            .select('*'),

          // 4. Get completed enrollments (progress = 100)
          supabase
            .from('enrollments')
            .select('course_id, enrolled_at, courses(title, category, image_url)')
            .eq('user_id', uid)
            .eq('progress', 100)
        ]);

        const dbCerts = certRes.data || [];
        const completedEnrollments = enrollmentRes.data || [];
        const earnedIds = earnedAchRes.data?.map(a => a.achievement_id) || [];
        const allBadges = allAchRes.data && allAchRes.data.length > 0 ? allAchRes.data : DEFAULT_ACHIEVEMENTS;

        // Merge certificates:
        // Start with manually issued certificates from the DB.
        const mergedCerts = [...dbCerts];

        // For any completed course that doesn't have a record in the certificates table, add a synthesized one.
        completedEnrollments.forEach(enrollment => {
          const hasIssuedCert = dbCerts.some(c => c.course_id === enrollment.course_id);
          if (!hasIssuedCert) {
            mergedCerts.push({
              id: `cert-${enrollment.course_id}`,
              course_id: enrollment.course_id,
              issued_at: enrollment.enrolled_at,
              certificate_url: null,
              courses: enrollment.courses,
              isAutoGenerated: true
            });
          }
        });

        const earned = allBadges.filter(b => earnedIds.includes(b.id));
        const locked = allBadges.filter(b => !earnedIds.includes(b.id));

        setCertificates(mergedCerts);
        setEarnedBadges(earned);
        setLockedBadges(locked);
        setStats({ certificates: mergedCerts.length, badges: earned.length });
      } else {
        const { data: allBadges } = await supabase.from('achievements').select('*');
        const badges = allBadges && allBadges.length > 0 ? allBadges : DEFAULT_ACHIEVEMENTS;
        
        // For guest, let's pre-unlock the "Pioneer" badge and mock a certificate so they can see how it looks
        const mockCert = {
          id: 'cert-mock-1',
          course_id: 1,
          issued_at: new Date().toISOString(),
          certificate_url: null,
          courses: {
            title: 'Dasar Pemrograman Web Modern',
            category: 'Technology',
            image_url: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=400'
          },
          isAutoGenerated: true
        };

        setCertificates([mockCert]);
        setEarnedBadges(badges.filter(b => b.id === 'pioneer'));
        setLockedBadges(badges.filter(b => b.id !== 'pioneer'));
        setStats({ certificates: 1, badges: 1 });
      }
      setLoading(false);
    };

    fetchData();
  }, [navigate, isGuest]);

  const formatDate = (d) =>
    d ? new Date(d).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Baru saja';

  const handlePrintCertificate = (cert) => {
    const printWindow = window.open('', '_blank', 'width=900,height=650');
    const formattedDate = cert.issued_at ? new Date(cert.issued_at).toLocaleDateString('id-ID', {
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    }) : new Date().toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });
    
    const studentName = profile?.fullName || profile?.full_name || "Pelajar Premium";
    const courseTitle = cert.courses?.title || "Kelas AiLearning";
    
    const rawId = cert.id && String(cert.id).startsWith('cert-') ? cert.id.replace('cert-', '') : cert.id;
    const certId = `CERT-${rawId || 'ONLINE'}-${String(profile?.id || 'GUEST').slice(0, 8).toUpperCase()}`;

    const content = `
      <div style="font-family:'Outfit', 'Inter', sans-serif; display:flex; justify-content:center; align-items:center; min-height:98vh; background:#fefefe; padding:20px; box-sizing:border-box;">
        <div style="width:100%; max-width:800px; border:10px double #000; padding:40px; background:#fffcf5; text-align:center; position:relative; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);">
          <div style="position:absolute; top:15px; left:15px; width:40px; height:40px; border-top:4px solid #000; border-left:4px solid #000;"></div>
          <div style="position:absolute; top:15px; right:15px; width:40px; height:40px; border-top:4px solid #000; border-right:4px solid #000;"></div>
          <div style="position:absolute; bottom:15px; left:15px; width:40px; height:40px; border-bottom:4px solid #000; border-left:4px solid #000;"></div>
          <div style="position:absolute; bottom:15px; right:15px; width:40px; height:40px; border-bottom:4px solid #000; border-right:4px solid #000;"></div>
          
          <div style="font-size:24px; font-weight:900; letter-spacing:4px; margin-bottom:20px; text-transform:uppercase;">AiLearning Academy</div>
          <div style="font-size:38px; font-weight:900; color:#000; text-transform:uppercase; margin-bottom:30px; border-bottom:4px solid #000; display:inline-block; padding-bottom:10px; letter-spacing:1px;">SERTIFIKAT KELULUSAN</div>
          
          <div style="font-size:16px; font-weight:700; color:#4b5563; margin-bottom:10px; text-transform:uppercase; letter-spacing:2px;">Diberikan Kepada</div>
          <div style="font-size:34px; font-weight:900; color:#000; text-decoration:underline; text-transform:capitalize; margin-bottom:25px; font-style:italic;">${studentName}</div>
          
          <div style="font-size:16px; font-weight:700; color:#4b5563; margin-bottom:10px; text-transform:uppercase; letter-spacing:2px;">Atas Keberhasilannya Menyelesaikan Kelas</div>
          <div style="font-size:26px; font-weight:900; color:#2563eb; margin-bottom:40px; line-height:1.3;">${courseTitle}</div>
          
          <div style="display:flex; justify-content:space-between; align-items:flex-end; margin-top:50px; padding:0 30px;">
            <div style="text-align:left;">
              <div style="font-size:12px; font-weight:700; color:#6b7280; text-transform:uppercase;">Tanggal Kelulusan</div>
              <div style="font-size:15px; font-weight:900; color:#000; margin-top:5px;">${formattedDate}</div>
            </div>
            <div style="text-align:center;">
              <div style="width:120px; height:2px; background:#000; margin-bottom:8px;"></div>
              <div style="font-size:12px; font-weight:900; text-transform:uppercase; color:#000;">Harin AI System</div>
              <div style="font-size:10px; font-weight:700; color:#6b7280;">Verifikasi Resmi</div>
            </div>
          </div>
          
          <div style="margin-top:40px; font-size:10px; font-weight:700; color:#9ca3af; letter-spacing:1px;">ID Verifikasi: ${certId}</div>
        </div>
      </div>
    `;

    printWindow.document.write(`
      <html>
        <head>
          <title>Sertifikat Kelulusan - ${studentName}</title>
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;700;900&display=swap" rel="stylesheet">
          <style>
            body { margin: 0; padding: 0; background-color: #ffffff; }
            @media print {
              body { background: none; }
              @page { size: landscape; margin: 0; }
            }
          </style>
        </head>
        <body>
          ${content}
          <script>
            window.onload = function() {
              setTimeout(function() {
                window.print();
                window.close();
              }, 500);
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="bg-surface text-on-surface font-body-md flex h-screen overflow-hidden">
      <Sidebar />

      <main className="flex-1 h-full overflow-y-auto bg-background p-8 md:p-10">
        {/* Header */}
        <header className="mb-12 border-b-4 border-on-surface pb-6 flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div>
            <h1 className="font-headline-xl text-on-surface mb-2 font-black">Pencapaian &amp; Sertifikat</h1>
            <p className="font-body-lg text-on-surface-variant">Lacak perkembangan belajarmu dan rayakan setiap langkah.</p>
          </div>
          <div className="flex gap-4">
            <div className="bg-primary-container border-4 border-on-surface shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] rounded-xl p-4 flex flex-col items-center justify-center min-w-[140px]">
              <span className="font-headline-md text-on-primary-container font-black">{stats.certificates}</span>
              <span className="font-label-bold text-on-surface-variant text-[10px] uppercase">Sertifikat</span>
            </div>
            <div className="bg-secondary-fixed border-4 border-on-surface shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] rounded-xl p-4 flex flex-col items-center justify-center min-w-[140px]">
              <span className="font-headline-md text-on-secondary-container font-black">{stats.badges}</span>
              <span className="font-label-bold text-on-surface-variant text-[10px] uppercase">Lencana</span>
            </div>
          </div>
        </header>

        {/* Sertifikat Saya */}
        <section className="mb-16">
          <div className="flex items-center gap-3 mb-8">
            <Icon name="workspace_premium" className="w-8 h-8 text-primary" />
            <h2 className="font-headline-lg text-on-surface font-black">Sertifikat Saya</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {loading ? (
              [1, 2].map(i => (
                <div key={i} className="h-64 bg-on-surface/5 animate-pulse border-4 border-on-surface rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]" />
              ))
            ) : certificates.length === 0 ? (
              <div className="col-span-full bg-surface-container-low border-4 border-dashed border-on-surface rounded-xl flex flex-col items-center justify-center p-12 text-center shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                <Icon name="school" className="w-16 h-16 text-on-surface-variant opacity-30 mb-4" />
                <h3 className="font-headline-md text-on-surface mb-2">Belum Ada Sertifikat</h3>
                <p className="font-body-md text-on-surface-variant mb-6">
                  Selesaikan semua materi kursus dan tunggu sertifikat dari guru.
                </p>
                <button
                  onClick={() => navigate('/catalog')}
                  className="bg-primary text-on-primary border-4 border-on-surface shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] rounded-lg py-2 px-8 font-label-bold hover:translate-x-[-2px] transition-all"
                >
                  Mulai Belajar
                </button>
              </div>
            ) : (
              certificates.map((cert, idx) => (
                <div
                  key={idx}
                  className="bg-white border-4 border-on-surface shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] rounded-xl flex flex-col overflow-hidden hover:translate-x-[-2px] hover:translate-y-[-2px] hover:shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] transition-all"
                >
                  {/* Certificate Image */}
                  <div className="h-48 bg-surface-variant border-b-4 border-on-surface relative flex items-center justify-center overflow-hidden">
                    {cert.certificate_url ? (
                      <img
                        src={cert.certificate_url}
                        alt="Sertifikat"
                        className="w-full h-full object-cover"
                      />
                    ) : (
                      <>
                        {cert.courses?.image_url && (
                          <img
                            alt="Course"
                            className="absolute inset-0 w-full h-full object-cover opacity-30"
                            src={cert.courses.image_url}
                          />
                        )}
                        <div className="relative z-10 bg-primary-container border-2 border-on-surface px-4 py-2 rounded-full rotate-[-5deg] font-black text-sm shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                          🎓 CERTIFIED
                        </div>
                      </>
                    )}
                  </div>

                  <div className="p-6 flex-1 flex flex-col">
                    <h3 className="font-headline-md text-on-surface mb-1 line-clamp-2">
                      {cert.courses?.title || 'Kursus'}
                    </h3>
                    <p className="text-xs font-bold text-on-surface-variant mb-1 uppercase">
                      {cert.courses?.category}
                    </p>
                    <p className="font-body-sm text-on-surface-variant mb-6 flex-1">
                      Diterbitkan: {formatDate(cert.issued_at)}
                    </p>

                    {cert.certificate_url ? (
                      <button
                        onClick={() => setSelectedCertForPreview(cert)}
                        className="w-full bg-secondary text-on-secondary border-4 border-on-surface shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] rounded-lg py-3 font-black text-sm flex items-center justify-center gap-2 hover:bg-secondary-container hover:text-on-secondary-container transition-all"
                      >
                        <Icon name="visibility" className="w-5 h-5" />
                        LIHAT SERTIFIKAT
                      </button>
                    ) : (
                      <button
                        onClick={() => setSelectedCertForPreview(cert)}
                        className="w-full bg-[#FFB800] hover:bg-[#e6a500] text-on-background border-4 border-on-surface shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] rounded-lg py-3 font-black text-sm flex items-center justify-center gap-2 hover:translate-x-[-2px] hover:translate-y-[-2px] hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] transition-all"
                      >
                        <Icon name="visibility" className="w-5 h-5" />
                        LIHAT SERTIFIKAT
                      </button>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>
        </section>

        {/* Badges Section */}
        <section>
          <div className="flex items-center gap-3 mb-8 pb-4 border-b-4 border-on-surface">
            <Icon name="military_tech" className="w-8 h-8 text-on-surface" />
            <h2 className="font-headline-lg text-on-surface font-black">Koleksi Lencana</h2>
          </div>

          <div className="grid grid-cols-1 xl:grid-cols-2 gap-10 pb-20">
            {/* Earned Badges */}
            <div className="bg-surface-container-low border-4 border-on-surface rounded-xl p-8 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
              <h3 className="font-headline-md text-on-surface mb-8 flex items-center gap-3">
                <Icon name="check_circle" className="w-6 h-6 text-primary" />
                Sudah Didapat
              </h3>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-6">
                {loading ? (
                  [1, 2, 3].map(i => (
                    <div key={i} className="aspect-square bg-on-surface/5 animate-pulse rounded-lg border-2 border-on-surface" />
                  ))
                ) : earnedBadges.length === 0 ? (
                  <p className="col-span-full text-center text-on-surface-variant font-bold opacity-50 py-10 italic">
                    Belum ada lencana yang didapat.
                  </p>
                ) : (
                  earnedBadges.map((badge, idx) => (
                    <div
                      key={idx}
                      className="bg-white border-2 border-on-surface rounded-lg p-4 flex flex-col items-center text-center shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-y-[-4px] transition-transform"
                    >
                      <div className={`w-16 h-16 ${badge.color_class} border-2 border-on-surface rounded-full flex items-center justify-center mb-3 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]`}>
                        <Icon name={badge.icon_name} className="w-8 h-8 text-on-surface" />
                      </div>
                      <span className="font-black text-on-surface text-[10px] uppercase leading-tight mb-1">{badge.title}</span>
                      <p className="text-[9px] text-on-surface-variant font-medium leading-tight">{badge.description}</p>
                    </div>
                  ))
                )}
              </div>
            </div>

            {/* Locked Badges */}
            <div className="bg-surface-variant border-4 border-on-surface rounded-xl p-8 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] opacity-70">
              <h3 className="font-headline-md text-on-surface-variant mb-8 flex items-center gap-3">
                <Icon name="lock" className="w-6 h-6" />
                Belum Terbuka
              </h3>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-6">
                {loading ? (
                  [1, 2].map(i => (
                    <div key={i} className="aspect-square bg-on-surface/5 animate-pulse rounded-lg border-2 border-on-surface" />
                  ))
                ) : lockedBadges.length === 0 ? (
                  <p className="col-span-full text-center text-on-surface-variant font-bold py-10">
                    Luar biasa! Semua lencana sudah terbuka.
                  </p>
                ) : (
                  lockedBadges.map((badge, idx) => (
                    <div
                      key={idx}
                      className="bg-surface-dim border-2 border-dashed border-on-surface rounded-lg p-4 flex flex-col items-center text-center"
                    >
                      <div className="w-16 h-16 bg-outline-variant border-2 border-dashed border-on-surface rounded-full flex items-center justify-center mb-3 grayscale opacity-30">
                        <Icon name={badge.icon_name} className="w-8 h-8" />
                      </div>
                      <span className="font-black text-on-surface-variant text-[10px] uppercase leading-tight mb-1">{badge.title}</span>
                      <p className="text-[9px] text-on-surface-variant italic leading-tight">Syarat: {badge.description}</p>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        </section>

        {/* Certificate Preview Modal */}
        {selectedCertForPreview && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
            <div className="bg-surface border-4 border-on-surface shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] rounded-2xl w-full max-w-3xl overflow-hidden flex flex-col relative animate-in fade-in zoom-in-95 duration-200">
              {/* Modal Header */}
              <div className="flex justify-between items-center p-4 border-b-2 border-on-surface bg-primary-container shrink-0">
                <span className="font-headline-sm font-black text-on-primary-container flex items-center gap-2">
                  <Icon name="workspace_premium" className="w-6 h-6 text-primary" />
                  Pratinjau Sertifikat
                </span>
                <button 
                  onClick={() => setSelectedCertForPreview(null)}
                  className="text-on-surface hover:text-error transition-colors p-1 bg-white/20 rounded-full border border-on-surface/10"
                >
                  <Icon name="close" className="w-6 h-6" />
                </button>
              </div>

              {/* Modal Content */}
              <div className="flex-1 overflow-y-auto p-6 md:p-8 bg-surface-container-lowest flex items-center justify-center min-h-[300px]">
                {selectedCertForPreview.certificate_url ? (
                  // Custom Certificate Preview
                  <div className="w-full max-w-2xl border-4 border-on-surface shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] overflow-hidden rounded-xl bg-white aspect-video relative">
                    {selectedCertForPreview.certificate_url.endsWith('.pdf') ? (
                      <iframe 
                        src={`${selectedCertForPreview.certificate_url}#toolbar=0`}
                        className="w-full h-full border-none"
                        title="PDF Preview"
                      />
                    ) : (
                      <img 
                        src={selectedCertForPreview.certificate_url}
                        alt="Sertifikat"
                        className="w-full h-full object-contain"
                      />
                    )}
                  </div>
                ) : (
                  // Auto-Generated Certificate HTML Preview
                  <div className="w-full max-w-2xl border-4 border-on-surface bg-[#fffcf5] p-6 md:p-10 text-center relative shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] font-sans" style={{ borderStyle: 'double', borderWidth: '10px' }}>
                    <div className="absolute top-3 left-3 w-8 h-8 border-t-2 border-l-2 border-on-surface border-t-black border-l-black"></div>
                    <div className="absolute top-3 right-3 w-8 h-8 border-t-2 border-r-2 border-on-surface border-t-black border-r-black"></div>
                    <div className="absolute bottom-3 left-3 w-8 h-8 border-b-2 border-l-2 border-on-surface border-b-black border-l-black"></div>
                    <div className="absolute bottom-3 right-3 w-8 h-8 border-b-2 border-r-2 border-on-surface border-b-black border-r-black"></div>
                    
                    <div className="text-[12px] md:text-sm font-black tracking-widest text-on-surface-variant/80 uppercase mb-2">AiLearning Academy</div>
                    <div className="text-xl md:text-3xl font-black text-on-surface border-b-2 border-on-surface inline-block pb-1 mb-4 uppercase">SERTIFIKAT KELULUSAN</div>
                    
                    <div className="text-[10px] md:text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1">Diberikan Kepada</div>
                    <div className="text-lg md:text-2xl font-black text-on-surface underline italic mb-4 capitalize">
                      {profile?.fullName || profile?.full_name || "Pelajar Premium"}
                    </div>
                    
                    <div className="text-[10px] md:text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1">Atas Keberhasilannya Menyelesaikan Kelas</div>
                    <div className="text-sm md:text-lg font-black text-primary leading-tight mb-6">
                      {selectedCertForPreview.courses?.title || "Kelas AiLearning"}
                    </div>
                    
                    <div className="flex justify-between items-end mt-4 md:mt-8 px-2 text-left">
                      <div>
                        <div className="text-[8px] md:text-[10px] font-bold text-on-surface-variant uppercase">Tanggal Kelulusan</div>
                        <div className="text-[10px] md:text-xs font-black text-on-surface mt-0.5">
                          {selectedCertForPreview.issued_at ? new Date(selectedCertForPreview.issued_at).toLocaleDateString('id-ID', {
                            day: 'numeric',
                            month: 'long',
                            year: 'numeric'
                          }) : 'Baru saja'}
                        </div>
                      </div>
                      <div className="text-center">
                        <div className="w-16 md:w-24 h-0.5 bg-on-surface mb-1"></div>
                        <div className="text-[8px] md:text-[10px] font-black uppercase text-on-surface">Harin AI System</div>
                        <div className="text-[6px] md:text-[8px] font-bold text-on-surface-variant">Verifikasi Resmi</div>
                      </div>
                    </div>
                    <div className="mt-4 md:mt-6 text-[8px] font-bold text-on-surface-variant/60 tracking-wider">
                      ID: CERT-{(selectedCertForPreview.id && String(selectedCertForPreview.id).startsWith('cert-') ? selectedCertForPreview.id.replace('cert-', '') : selectedCertForPreview.id || 'ONLINE').toUpperCase()}-{String(profile?.id || 'GUEST').slice(0, 8).toUpperCase()}
                    </div>
                  </div>
                )}
              </div>

              {/* Modal Footer */}
              <div className="p-4 border-t-2 border-on-surface bg-surface-container flex justify-end gap-3 shrink-0">
                <button
                  onClick={() => setSelectedCertForPreview(null)}
                  className="px-5 py-2 bg-white text-on-surface border-2 border-on-surface shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] rounded-lg font-bold text-sm hover:bg-surface-container transition-all"
                >
                  Tutup
                </button>
                {selectedCertForPreview.certificate_url ? (
                  <a
                    href={selectedCertForPreview.certificate_url}
                    download
                    target="_blank"
                    rel="noopener noreferrer"
                    className="px-5 py-2 bg-primary text-white border-2 border-on-surface shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] rounded-lg font-black text-sm hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] transition-all flex items-center gap-2"
                  >
                    <Icon name="download" className="w-4 h-4" />
                    Unduh / Simpan PDF
                  </a>
                ) : (
                  <button
                    onClick={() => handlePrintCertificate(selectedCertForPreview)}
                    className="px-5 py-2 bg-[#FFB800] text-on-background border-2 border-on-surface shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] rounded-lg font-black text-sm hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] transition-all flex items-center gap-2"
                  >
                    <Icon name="print" className="w-4 h-4" />
                    Cetak / Simpan PDF
                  </button>
                )}
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default Achievements;
