-- =========================================================================
-- DATABASE FULL SETUP SCRIPT FOR LUMINA MONOREPO (HARIN LEARNING)
-- =========================================================================
-- Jalankan skrip ini sekali saja di SQL Editor Supabase Anda untuk 
-- menginisialisasi seluruh tabel, relasi, kebijakan RLS, dan fungsi RPC.
-- Skrip ini dirancang aman dijalankan berulang kali (Idempotent).
-- =========================================================================

-- JIKA INGIN MERESET TOTAL DATABASE (HAPUS SEMUA DATA & TABEL LAMA):
-- Hapus tanda "--" pada baris di bawah ini dan jalankan jika ingin memulai dari nol:
-- DROP TABLE IF EXISTS profiles, courses, enrollments, wishlist, cart, posts, study_plans, achievements, user_achievements, notifications, notification_reads, course_categories, course_sections, course_syllabus, user_progress, certificates, submissions, course_collaborators, communities, community_members, channels, community_messages, friends, direct_messages, channel_admins CASCADE;

-- 1. AKTIFKAN EKSTENSI POSTGRESQL YANG DIBUTUHKAN
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. TABEL PROFIL PENGGUNA (Terhubung ke Supabase Auth.users)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  username TEXT UNIQUE,
  avatar_url TEXT,
  role TEXT DEFAULT 'student',
  friend_code TEXT UNIQUE DEFAULT substring(md5(random()::text) from 1 for 6),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. TABEL KURSUS (Courses)
CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  instructor TEXT NOT NULL,
  instructor_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  price DECIMAL NOT NULL,
  image_url TEXT,
  category TEXT,
  description TEXT,
  status TEXT DEFAULT 'draft',
  level TEXT DEFAULT 'beginner',
  language TEXT DEFAULT 'id',
  what_will_learn JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. TABEL ENROLLMENT (Pembelian / Pendaftaran Kursus)
CREATE TABLE IF NOT EXISTS enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  progress INT DEFAULT 0,
  enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, course_id)
);

-- 5. TABEL WISHLIST
CREATE TABLE IF NOT EXISTS wishlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  added_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, course_id)
);

-- 6. TABEL KERANJANG BELANJA (Cart)
CREATE TABLE IF NOT EXISTS cart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  added_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, course_id)
);

-- 7. TABEL POSTINGAN BLOG
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT,
  image_url TEXT,
  author_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  views INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. TABEL RENCANA BELAJAR AI (Study Plans)
CREATE TABLE IF NOT EXISTS study_plans (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  text TEXT NOT NULL,
  done BOOLEAN DEFAULT false,
  duration TEXT DEFAULT '',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 9. TABEL MASTER PENCAPAIAN (Achievements)
CREATE TABLE IF NOT EXISTS achievements (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  icon_name TEXT NOT NULL,
  color_class TEXT NOT NULL
);

-- 10. TABEL PENCAPAIAN PENGGUNA (User Achievements)
CREATE TABLE IF NOT EXISTS user_achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  achievement_id TEXT REFERENCES achievements ON DELETE CASCADE NOT NULL,
  earned_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, achievement_id)
);

-- 11. TABEL NOTIFIKASI
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE, -- NULL berarti NOTIFIKASI GLOBAL
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT CHECK (type IN ('course', 'blog', 'system', 'achievement')),
  link_to TEXT,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 12. TABEL BACA NOTIFIKASI INDIVIDUAL (Untuk Notifikasi Global)
CREATE TABLE IF NOT EXISTS notification_reads (
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  notification_id BIGINT REFERENCES notifications ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (user_id, notification_id)
);

-- 13. TABEL KATEGORI KURSUS
CREATE TABLE IF NOT EXISTS course_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 14. TABEL BAGIAN KURSUS (Course Sections)
CREATE TABLE IF NOT EXISTS course_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 15. TABEL SILABUS KURSUS (Materi & Tugas)
CREATE TABLE IF NOT EXISTS course_syllabus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id BIGINT REFERENCES course_sections ON DELETE CASCADE NOT NULL,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  file_url TEXT,
  video_url TEXT,
  assignment_text TEXT,
  initial_code TEXT,
  test_cases JSONB,
  solution_code TEXT,
  programming_language TEXT DEFAULT 'javascript',
  sort_order INT DEFAULT 0,
  is_published BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 16. TABEL PROGRESS BELAJAR SISWA
CREATE TABLE IF NOT EXISTS user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  syllabus_id BIGINT REFERENCES course_syllabus ON DELETE CASCADE NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, syllabus_id)
);

-- 17. TABEL SERTIFIKAT KELULUSAN
CREATE TABLE IF NOT EXISTS certificates (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  issued_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 18. TABEL SUBMISSION (Pengumpulan Tugas Siswa)
CREATE TABLE IF NOT EXISTS submissions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  syllabus_id BIGINT REFERENCES course_syllabus ON DELETE CASCADE NOT NULL,
  file_url TEXT,
  assignment_text TEXT,
  status TEXT DEFAULT 'pending',
  grade INT,
  feedback TEXT,
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(student_id, syllabus_id)
);

-- 19. TABEL KOLABORATOR KURSUS (Guru Tambahan)
CREATE TABLE IF NOT EXISTS course_collaborators (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  teacher_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  role TEXT DEFAULT 'editor',
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(course_id, teacher_id)
);

-- 20. TABEL KOMUNITAS (Communities)
CREATE TABLE IF NOT EXISTS communities (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT,
  accent_color TEXT DEFAULT '#3b82f6',
  invite_code TEXT UNIQUE DEFAULT substring(md5(random()::text) from 1 for 8),
  created_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 21. TABEL ANGGOTA KOMUNITAS
CREATE TABLE IF NOT EXISTS community_members (
  community_id UUID REFERENCES communities(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'member')),
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  PRIMARY KEY (community_id, user_id)
);

-- 22. TABEL SALURAN KOMUNITAS (Channels)
CREATE TABLE IF NOT EXISTS channels (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  community_id UUID REFERENCES communities(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT DEFAULT 'text' CHECK (type IN ('text', 'voice')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 23. TABEL PESAN KOMUNITAS (Community Messages)
CREATE TABLE IF NOT EXISTS community_messages (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  channel_id UUID REFERENCES channels(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 24. TABEL PERTEMANAN (Friends)
CREATE TABLE IF NOT EXISTS friends (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  friend_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  PRIMARY KEY (user_id, friend_id)
);

-- 25. TABEL PESAN LANGSUNG (Direct Messages)
CREATE TABLE IF NOT EXISTS direct_messages (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  receiver_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 26. TABEL ADMIN SALURAN (Channel Admins)
CREATE TABLE IF NOT EXISTS channel_admins (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  channel_id UUID REFERENCES channels(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(channel_id, user_id)
);


-- =========================================================================
-- 27. FUNGI & RPC (REMOTE PROCEDURE CALLS)
-- =========================================================================

-- RPC: Bergabung ke Komunitas dengan Kode Undangan
CREATE OR REPLACE FUNCTION join_community(invite_code_input TEXT)
RETURNS UUID AS $$
DECLARE
  target_comm_id UUID;
BEGIN
  SELECT id INTO target_comm_id FROM communities WHERE invite_code = invite_code_input;
  
  IF target_comm_id IS NULL THEN
    RETURN NULL;
  END IF;

  INSERT INTO community_members (community_id, user_id, role)
  VALUES (target_comm_id, auth.uid(), 'member')
  ON CONFLICT (community_id, user_id) DO NOTHING;

  RETURN target_comm_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: Tambah Teman Menggunakan Friend Code
CREATE OR REPLACE FUNCTION add_friend_by_code(friend_code_input TEXT)
RETURNS BOOLEAN AS $$
DECLARE
  target_user_id UUID;
BEGIN
  SELECT id INTO target_user_id FROM profiles WHERE friend_code = friend_code_input;
  
  IF target_user_id IS NULL OR target_user_id = auth.uid() THEN
    RETURN FALSE;
  END IF;

  INSERT INTO friends (user_id, friend_id)
  VALUES (auth.uid(), target_user_id)
  ON CONFLICT (user_id, friend_id) DO NOTHING;

  INSERT INTO friends (user_id, friend_id)
  VALUES (target_user_id, auth.uid())
  ON CONFLICT (user_id, friend_id) DO NOTHING;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper: Mengecek apakah pengguna adalah manager komunitas
CREATE OR REPLACE FUNCTION is_community_manager(comm_id UUID, u_id UUID) 
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM community_members 
    WHERE community_id = comm_id AND user_id = u_id AND role IN ('owner', 'admin')
  );
END;
$$ LANGUAGE plpgsql;


-- =========================================================================
-- 28. KEBIJAKAN KEAMANAN RLS (ROW LEVEL SECURITY)
-- =========================================================================

-- Aktifkan RLS di setiap tabel
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_syllabus ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_collaborators ENABLE ROW LEVEL SECURITY;
ALTER TABLE communities ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE friends ENABLE ROW LEVEL SECURITY;
ALTER TABLE direct_messages ENABLE ROW LEVEL SECURITY;

-- BERSIHKAN KEBIJAKAN LAMA JIKA ADA (Mencegah Error Duplicate)
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON profiles;
DROP POLICY IF EXISTS "Users can insert their own profile." ON profiles;
DROP POLICY IF EXISTS "Users can update own profile." ON profiles;
DROP POLICY IF EXISTS "Allow insert for own profile" ON profiles;
DROP POLICY IF EXISTS "Allow update for own profile" ON profiles;

DROP POLICY IF EXISTS "Courses are viewable by everyone." ON courses;
DROP POLICY IF EXISTS "Teachers can insert their own courses" ON courses;
DROP POLICY IF EXISTS "Teachers can update their own courses" ON courses;
DROP POLICY IF EXISTS "Teachers can delete their own courses" ON courses;

DROP POLICY IF EXISTS "Users can view their own enrollments." ON enrollments;
DROP POLICY IF EXISTS "Users can update their own enrollments." ON enrollments;
DROP POLICY IF EXISTS "Users can insert their own enrollments." ON enrollments;

DROP POLICY IF EXISTS "Users can manage their own wishlist." ON wishlist;
DROP POLICY IF EXISTS "Users can manage their own cart." ON cart;

DROP POLICY IF EXISTS "Posts are viewable by everyone." ON posts;
DROP POLICY IF EXISTS "Users can insert their own posts." ON posts;
DROP POLICY IF EXISTS "Users can update their own posts." ON posts;
DROP POLICY IF EXISTS "Users can delete their own posts." ON posts;

DROP POLICY IF EXISTS "Users can view their own study plans." ON study_plans;
DROP POLICY IF EXISTS "Users can insert their own study plans." ON study_plans;
DROP POLICY IF EXISTS "Users can update their own study plans." ON study_plans;
DROP POLICY IF EXISTS "Users can delete their own study plans." ON study_plans;

DROP POLICY IF EXISTS "Achievements are viewable by everyone" ON achievements;
DROP POLICY IF EXISTS "Users can view their own achievements" ON user_achievements;
DROP POLICY IF EXISTS "Users can earn achievements" ON user_achievements;

DROP POLICY IF EXISTS "Users can view own or global notifications" ON notifications;
DROP POLICY IF EXISTS "Anyone can insert notifications" ON notifications;
DROP POLICY IF EXISTS "Users can manage their own read status" ON notification_reads;

DROP POLICY IF EXISTS "Categories viewable by everyone" ON course_categories;
DROP POLICY IF EXISTS "Teachers can insert categories" ON course_categories;
DROP POLICY IF EXISTS "Sections viewable by everyone" ON course_sections;
DROP POLICY IF EXISTS "Teachers can manage sections" ON course_sections;
DROP POLICY IF EXISTS "Syllabus viewable by everyone" ON course_syllabus;
DROP POLICY IF EXISTS "Teachers can manage syllabus" ON course_syllabus;
DROP POLICY IF EXISTS "Users can view and manage own progress" ON user_progress;
DROP POLICY IF EXISTS "Users can view own certificates" ON certificates;
DROP POLICY IF EXISTS "Users can manage their own submissions" ON submissions;
DROP POLICY IF EXISTS "Teachers can view all submissions" ON submissions;
DROP POLICY IF EXISTS "Collaborators are viewable by everyone" ON course_collaborators;
DROP POLICY IF EXISTS "Teachers can manage collaborators" ON course_collaborators;

-- RLS UNTUK KOMUNITAS & CHAT
DROP POLICY IF EXISTS "Anyone can view communities" ON communities;
DROP POLICY IF EXISTS "Authenticated users can create communities" ON communities;
DROP POLICY IF EXISTS "Owners and Admins can update community" ON communities;
DROP POLICY IF EXISTS "Owners can delete community" ON communities;
DROP POLICY IF EXISTS "Anyone can view members" ON community_members;
DROP POLICY IF EXISTS "Anyone can join communities" ON community_members;
DROP POLICY IF EXISTS "Managers can manage members" ON community_members;
DROP POLICY IF EXISTS "Managers can delete members" ON community_members;
DROP POLICY IF EXISTS "Anyone can view channels" ON channels;
DROP POLICY IF EXISTS "Managers can create channels" ON channels;
DROP POLICY IF EXISTS "Managers can update channels" ON channels;
DROP POLICY IF EXISTS "Managers can delete channels" ON channels;
DROP POLICY IF EXISTS "Anyone can view messages" ON community_messages;
DROP POLICY IF EXISTS "Users can send messages" ON community_messages;
DROP POLICY IF EXISTS "Users can view their friends" ON friends;
DROP POLICY IF EXISTS "Users can view their DMs" ON direct_messages;
DROP POLICY IF EXISTS "Users can send DMs" ON direct_messages;


-- BUAT KEBIJAKAN BARU SECARA AMAN
-- Profiles
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Courses
CREATE POLICY "Courses are viewable by everyone." ON courses FOR SELECT USING (true);
CREATE POLICY "Teachers can insert their own courses" ON courses FOR INSERT WITH CHECK (auth.uid() = instructor_id);
CREATE POLICY "Teachers can update their own courses" ON courses FOR UPDATE USING (auth.uid() = instructor_id);
CREATE POLICY "Teachers can delete their own courses" ON courses FOR DELETE USING (auth.uid() = instructor_id);

-- Enrollments
CREATE POLICY "Users can view their own enrollments." ON enrollments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own enrollments." ON enrollments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own enrollments." ON enrollments FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Wishlist & Cart
CREATE POLICY "Users can manage their own wishlist." ON wishlist FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own cart." ON cart FOR ALL USING (auth.uid() = user_id);

-- Posts
CREATE POLICY "Posts are viewable by everyone." ON posts FOR SELECT USING (true);
CREATE POLICY "Users can insert their own posts." ON posts FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Users can update their own posts." ON posts FOR UPDATE USING (auth.uid() = author_id);
CREATE POLICY "Users can delete their own posts." ON posts FOR DELETE USING (auth.uid() = author_id);

-- Study Plans
CREATE POLICY "Users can view their own study plans." ON study_plans FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own study plans." ON study_plans FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own study plans." ON study_plans FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own study plans." ON study_plans FOR DELETE USING (auth.uid() = user_id);

-- Achievements & Badges
CREATE POLICY "Achievements are viewable by everyone" ON achievements FOR SELECT USING (true);
CREATE POLICY "Users can view their own achievements" ON user_achievements FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can earn achievements" ON user_achievements FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Notifications
CREATE POLICY "Users can view own or global notifications" ON notifications FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "Anyone can insert notifications" ON notifications FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can manage their own read status" ON notification_reads FOR ALL USING (auth.uid() = user_id);

-- Syllabus & Sections
CREATE POLICY "Categories viewable by everyone" ON course_categories FOR SELECT USING (true);
CREATE POLICY "Teachers can insert categories" ON course_categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Sections viewable by everyone" ON course_sections FOR SELECT USING (true);
CREATE POLICY "Teachers can manage sections" ON course_sections FOR ALL USING (true);
CREATE POLICY "Syllabus viewable by everyone" ON course_syllabus FOR SELECT USING (true);
CREATE POLICY "Teachers can manage syllabus" ON course_syllabus FOR ALL USING (true);

-- Progress, Certificates & Submissions
CREATE POLICY "Users can view and manage own progress" ON user_progress FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can view own certificates" ON certificates FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own submissions" ON submissions FOR ALL USING (auth.uid() = student_id);
CREATE POLICY "Teachers can view all submissions" ON submissions FOR SELECT USING (true);
CREATE POLICY "Collaborators are viewable by everyone" ON course_collaborators FOR SELECT USING (true);
CREATE POLICY "Teachers can manage collaborators" ON course_collaborators FOR ALL USING (true);

-- Communities & Chat
CREATE POLICY "Anyone can view communities" ON communities FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can create communities" ON communities FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by);
CREATE POLICY "Owners and Admins can update community" ON communities FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM community_members WHERE community_id = communities.id AND user_id = auth.uid() AND role = 'owner')
);
CREATE POLICY "Owners can delete community" ON communities FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM community_members WHERE community_id = communities.id AND user_id = auth.uid() AND role = 'owner')
);

CREATE POLICY "Anyone can view members" ON community_members FOR SELECT TO authenticated USING (true);
CREATE POLICY "Anyone can join communities" ON community_members FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Managers can manage members" ON community_members FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM community_members WHERE community_id = community_members.community_id AND user_id = auth.uid() AND role IN ('owner', 'admin'))
);
CREATE POLICY "Managers can delete members" ON community_members FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM community_members WHERE community_id = community_members.community_id AND user_id = auth.uid() AND role IN ('owner', 'admin'))
);

CREATE POLICY "Anyone can view channels" ON channels FOR SELECT TO authenticated USING (true);
CREATE POLICY "Managers can create channels" ON channels FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM community_members WHERE community_id = channels.community_id AND user_id = auth.uid() AND role IN ('owner', 'admin'))
);
CREATE POLICY "Managers can update channels" ON channels FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM community_members WHERE community_id = channels.community_id AND user_id = auth.uid() AND role IN ('owner', 'admin')) OR 
  EXISTS (SELECT 1 FROM channel_admins WHERE channel_id = channels.id AND user_id = auth.uid())
);
CREATE POLICY "Managers can delete channels" ON channels FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM community_members WHERE community_id = channels.community_id AND user_id = auth.uid() AND role IN ('owner', 'admin'))
);

CREATE POLICY "Anyone can view messages" ON community_messages FOR SELECT USING (true);
CREATE POLICY "Users can send messages" ON community_messages FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their friends" ON friends FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can view their DMs" ON direct_messages FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY "Users can send DMs" ON direct_messages FOR INSERT WITH CHECK (auth.uid() = sender_id);


-- =========================================================================
-- 29. INPUT DATA AWAL (INITIAL MASTER DATA)
-- =========================================================================

-- Data Awal Achievements
INSERT INTO achievements (id, title, description, icon_name, color_class) VALUES
('pioneer', 'Pioneer', 'Bergabung dengan Harin Learning.', 'history_edu', 'bg-primary-container'),
('first_step', 'First Step', 'Mengambil kursus pertama.', 'rocket_launch', 'bg-secondary-container'),
('scholar', 'Scholar', 'Menyelesaikan 1 kursus.', 'workspace_premium', 'bg-tertiary-container'),
('author', 'Author', 'Menulis postingan blog pertama.', 'edit_note', 'bg-primary-fixed'),
('top_student', 'Top Student', 'Memiliki 5+ kursus aktif.', 'star', 'bg-secondary-fixed')
ON CONFLICT (id) DO NOTHING;

-- Data Awal Kategori Kursus
INSERT INTO course_categories (name) VALUES 
('Technology'), 
('Design'), 
('Business'), 
('Marketing') 
ON CONFLICT (name) DO NOTHING;


-- =========================================================================
-- 30. STORAGE POLICY SETUP
-- =========================================================================
-- Pastikan Anda sudah membuat bucket "avatars" & "syllabus_files" 
-- secara manual di dashboard Supabase terlebih dahulu dengan mencentang "Public bucket".

-- Izinkan akses publik untuk melihat berkas storage
DROP POLICY IF EXISTS "Avatar Public Access" ON storage.objects;
CREATE POLICY "Avatar Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Syllabus Public Access" ON storage.objects;
CREATE POLICY "Syllabus Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'syllabus_files');

-- Izinkan unggahan berkas oleh pemilik/user yang login
DROP POLICY IF EXISTS "Users can upload their own avatar" ON storage.objects;
CREATE POLICY "Users can upload their own avatar" ON storage.objects FOR INSERT WITH CHECK (
  bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]
);

DROP POLICY IF EXISTS "Users can update/delete their own avatar" ON storage.objects;
CREATE POLICY "Users can update/delete their own avatar" ON storage.objects FOR ALL USING (
  bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]
);

DROP POLICY IF EXISTS "Users can upload syllabus files" ON storage.objects;
CREATE POLICY "Users can upload syllabus files" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'syllabus_files');


-- =========================================================================
-- 31. PUBLICATION SETUP (REALTIME PUSH NOTIFICATION)
-- =========================================================================
-- Mengaktifkan realtime agar push notification dan chat berjalan secara instan.
-- Kita bungkus dengan pengecekan aman agar tidak menghasilkan error duplikat.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime'
  ) THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
  
  -- Menambahkan tabel notifications ke publication secara aman
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
  EXCEPTION
    WHEN duplicate_object THEN
      NULL; -- abaikan jika sudah ditambahkan
  END;

  -- Menambahkan tabel community_messages ke publication secara aman
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE community_messages;
  EXCEPTION
    WHEN duplicate_object THEN
      NULL; -- abaikan jika sudah ditambahkan
  END;
END $$;
